### ISSUE TITLE
CPU and Memory Requests and Limits?

### ISSUE THREAD

**Issue by StevenACoffman** [fluent/fluent-bit-kubernetes-logging#14]
What would be a good set of CPU and memory requests and limits? For comparison, this is filebeat:
```
        resources:
          requests:
            cpu: 2m
            memory: 10Mi
          limits:
            cpu: 10m
            memory: 20Mi
```
I know that the documentation talks about Memory limits being dependent on the buffer amount.
> So, if we impose a limit of 10MB for the input plugins and considering the worse case scenario of the output plugin consuming 20MB extra, as a minimum we need (30MB x 1.2) = 36MB.

Given the `Mem_Buf_Limit     5MB`, would we need 13 MB?
