### ISSUE TITLE
fail to run fluent-bit-ds on kubernetes v1.16.2 (output to elasticsearch)

### ISSUE THREAD

**Issue by Goddywu** [fluent/fluent-bit-kubernetes-logging#61]
1. api version: extensions/v1beta1 is not support DaemonSet. 
2. spec needs selector
3. I changed es service name to elasticsearch-01-service

base on above, my `fluent-bit-ds.yaml` is
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
      version: v1
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: registry.cn-hangzhou.aliyuncs.com/mykg/fluent-bit:1.2.1
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch-01-service"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
```

then my pod start failed 

![image](https://user-images.githubusercontent.com/29056050/69320242-bf680f00-0c7b-11ea-8db5-6f27be4762c5.png)

logs is

![image](https://user-images.githubusercontent.com/29056050/69320261-cdb62b00-0c7b-11ea-86d0-a99ce3dcbe86.png)
