### ISSUE TITLE
Missing required field "selector" in DaemonSet spec for Elasticsearch

### ISSUE THREAD

**Issue by CAlexPac** [fluent/fluent-bit-kubernetes-logging#78]
After changing the apiVersion value to apps/v1, now I have an issue with the missing selector for the spec section.
What should the value be?
I've tried with:
```
  selector:
    matchLabels:
      name: fluent-bit
```
but it does not work.

**Comment by holyevyl** [comment]
Facing the same problem even for Kafka DaemonSet

**Comment by pardhasm** [comment]
I also faced the same issue. It god fixed after trying with

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
```
@CAlexPac  you have to give one of the labels of the DS.
