### ISSUE TITLE
extra line in fluent-bit role file for 1.22

### ISSUE THREAD

**Issue by lucj** [fluent/fluent-bit-kubernetes-logging#93]
I got the following error when creating the fluent-bit role on a 1.22 cluster:

````
error: error parsing https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/fluent-bit-role-1.22.yaml
````

This is due to a remaining "git diff" at the end of the file:

````
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
diff --git a/fluent-bit-role-binding-1.22.yaml b/fluent-bit-role-binding-1.22.yaml
````
